# Generated by Django 4.2 on 2025-01-27 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pauir_payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_payment', to=settings.AUTH_USER_MODEL),
        ),
    ]
